# Generated by Django 5.2.4 on 2025-08-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Product Information', 'Product Information'), ('Order Inquiry', 'Order Inquiry'), ('Technical Support', 'Technical Support'), ('Partnership', 'Partnership')], max_length=50),
        ),
    ]
